### ISSUE TITLE
Go through easy code and write CONTRIBUTING.md

### ISSUE THREAD

**Issue by 48cfu** [48cfu/game_of_life#3]
Give details on how to contribute and build upon

**Comment by Tawishi** [comment]
Can I take up this issue ?

**Comment by Tawishi** [comment]
Do the details have to be specific to the Game of Life code or does it have to explain general GitFlow?

**Comment by Tawishi** [comment]
What IDE do I use to run the code ?

**Comment by Tawishi** [comment]
Do you want the contributor to follow any Coding Guidelines ? Please, specify, if any.

**Comment by 48cfu** [comment]
> Do the details have to be specific to the Game of Life code or does it have to explain general GitFlow?

General GitFlow with some extra information on how to implement the extensions discussed in other issues would suffix.

**Comment by 48cfu** [comment]
> What IDE do I use to run the code ?

I use Eclipse IDE for C/C++ Developers.
The Instruction in Eclipse are: 
(please delete .cproject and .project from your branch before importing it to eclipse. If possible add them to .gitignore)
File -> Import... -> Git -> Projects from Git -> Clone URI
Set URI GIT_CLONE_URI
Insert your authentication details, and then click Next
Choose your branch/branches then Next
Choose Destination directory (or use suggested one). Set your Initial Branch. Then Next.
Choose Import Using the New Project Wizard. Then Finish.
Select a wizard: C/C++ -> C/C++ Project
Templates for New C/C++ Project: Select CMake -> Empty or Existing CMake Project, then Next.
Choose a Project name. For example: game-of-life. Then Finish.

**Comment by 48cfu** [comment]
> Do you want the contributor to follow any Coding Guidelines ? Please, specify, if any.

Not really at this point. Code should be commented and tested

**Comment by 48cfu** [comment]
> > What IDE do I use to run the code ?
> 
> I use Eclipse IDE for C/C++ Developers.
> The Instruction in Eclipse are:
> (please delete .cproject and .project from your branch before importing it to eclipse. If possible add them to .gitignore)
> File -> Import... -> Git -> Projects from Git -> Clone URI
> Set URI GIT_CLONE_URI
> Insert your authentication details, and then click Next
> Choose your branch/branches then Next
> Choose Destination directory (or use suggested one). Set your Initial Branch. Then Next.
> Choose Import Using the New Project Wizard. Then Finish.
> Select a wizard: C/C++ -> C/C++ Project
> Templates for New C/C++ Project: Select CMake -> Empty or Existing CMake Project, then Next.
> Choose a Project name. For example: game-of-life. Then Finish.

These instructions could be added to the README.md

**Comment by Tawishi** [comment]
What are the prerequisites for becoming a contributor?

**Comment by Tawishi** [comment]
> > What IDE do I use to run the code ?
> 
> I use Eclipse IDE for C/C++ Developers.
> The Instruction in Eclipse are:
> (please delete .cproject and .project from your branch before importing it to eclipse. If possible add them to .gitignore)
> File -> Import... -> Git -> Projects from Git -> Clone URI
> Set URI GIT_CLONE_URI
> Insert your authentication details, and then click Next
> Choose your branch/branches then Next
> Choose Destination directory (or use suggested one). Set your Initial Branch. Then Next.
> Choose Import Using the New Project Wizard. Then Finish.
> Select a wizard: C/C++ -> C/C++ Project
> Templates for New C/C++ Project: Select CMake -> Empty or Existing CMake Project, then Next.
> Choose a Project name. For example: game-of-life. Then Finish.

I am having trouble authenticating Git. Please help.

**Comment by Tawishi** [comment]
> > What IDE do I use to run the code ?
> 
> I use Eclipse IDE for C/C++ Developers.
> The Instruction in Eclipse are:
> (please delete .cproject and .project from your branch before importing it to eclipse. If possible add them to .gitignore)
> File -> Import... -> Git -> Projects from Git -> Clone URI
> Set URI GIT_CLONE_URI
> Insert your authentication details, and then click Next
> Choose your branch/branches then Next
> Choose Destination directory (or use suggested one). Set your Initial Branch. Then Next.
> Choose Import Using the New Project Wizard. Then Finish.
> Select a wizard: C/C++ -> C/C++ Project
> Templates for New C/C++ Project: Select CMake -> Empty or Existing CMake Project, then Next.
> Choose a Project name. For example: game-of-life. Then Finish.

I am having trouble in filling up the authentication details. Kindly help.
![issue2](https://user-images.githubusercontent.com/55306738/66453503-2e015c80-ea82-11e9-9302-30f67b6ce8cc.jpg)

**Comment by 48cfu** [comment]
All you need now is to type your git account detail:
user: Tawishi
password: your git password
Leave the port blank

**Comment by Tawishi** [comment]
Thank you for your time.

**Comment by Tawishi** [comment]
The following set of images shows what the README.md looks like.
![readme1](https://user-images.githubusercontent.com/55306738/66489186-d1775f00-eacc-11e9-9eed-7b4ff4c73b7c.jpg)
![readme2](https://user-images.githubusercontent.com/55306738/66489188-d1775f00-eacc-11e9-86ef-9a8cdb193569.jpg)
![readme3](https://user-images.githubusercontent.com/55306738/66489190-d1775f00-eacc-11e9-9859-12ee8c83c0ea.jpg)
![readme4](https://user-images.githubusercontent.com/55306738/66489192-d20ff580-eacc-11e9-9bee-2c7273e85cff.jpg)
![readme5](https://user-images.githubusercontent.com/55306738/66489193-d20ff580-eacc-11e9-9cc8-d73e94b63fb7.jpg)

**Please review and suggest any necessary changes.**

**Comment by Tawishi** [comment]
The following images show what *README.md* looks like now.

![readme1](https://user-images.githubusercontent.com/55306738/66489417-38951380-eacd-11e9-8c13-63873f563873.jpg)

![readme2](https://user-images.githubusercontent.com/55306738/66489545-6a0ddf00-eacd-11e9-84fa-c5178bae0ef8.jpg)

![readme3](https://user-images.githubusercontent.com/55306738/66489562-7003c000-eacd-11e9-8832-be7e44e33ca5.jpg)

![readme4](https://user-images.githubusercontent.com/55306738/66489574-75f9a100-eacd-11e9-94cb-64b5c5c567b9.jpg)

![readme5](https://user-images.githubusercontent.com/55306738/66489592-7d20af00-eacd-11e9-9d0d-db41ede93558.jpg)


**Please review and suggest the changes needed.**

**Comment by 48cfu** [comment]
I really appreciate your effort, thanks.
Please make a pull request and I can give you review directly on your contribution.

**Comment by Tawishi** [comment]
Done.
